name: Node CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Install pytest 🔧
      run: |
        pip3 install pytest pytest-cov
      env:
        CI: true
    
    - name: Run unittests with pytest 🔧
      run: |
        pytest -v --cov=src .\tests\ --junit-xml tests/results.xml
      env:
        CI: true
    
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: "tests/results.xml"
